# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
	backend "s3" {
		bucket = "vumatel-tf-state"
		dynamodb_table = "tf-state-lock"
		encrypt = true
		key = "uat/env/dev/env/uat"
		profile = "vumatel-operations"
		region = "af-south-1"
	}
}
