# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
	required_providers {
		aws = {
			source = "hashicorp/aws"
			version = "~> 4.0"
		}
		helm = {
			source = "hashicorp/helm"
			version = "~> 2.0"
		}
	}
}

provider aws {
	region = module.constants_cluster.aws_region
	profile = module.constants_cluster.aws_profile
}

provider helm {
	kubernetes {
		config_context = local.k8s_context
	}
}

provider aws {
	region = "eu-west-1"
	alias = "eu"
	profile = module.constants_cluster.aws_profile
}

provider aws {
	alias = "transit"
	profile = "vumatel-transit"
	region = "af-south-1"
}
