all:
  children:
    speedtest_servers:
      hosts:
        cpt:
          ansible_host: 102.220.178.3
          hostname: "cpt.open-speed-test.vumatel.vumaex.net"
          region: "WC"
        dbn:
          ansible_host: 102.220.179.3
          hostname: "dbn.open-speed-test.vumatel.vumaex.net"   
          region: "KZN"
        jhb:
          ansible_host: 102.220.176.3
          hostname: "jhb.open-speed-test.vumatel.vumaex.net"
          region: "GP"