apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      containers:
        - name: mock-server
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENV
              value: {{ .Values.env.ENVIRONMENT }}
            - name: MOCKSERVER_WATCH_INITIALIZATION_JSON 
              value: {{ .Values.env.MOCKSERVER_WATCH_INITIALIZATION_JSON | quote }}
            - name: MOCKSERVER_PROPERTY_FILE
              value: {{ .Values.env.MOCKSERVER_PROPERTY_FILE }}
            - name: MOCKSERVER_INITIALIZATION_JSON_PATH
              value: {{ .Values.env.MOCKSERVER_INITIALIZATION_JSON_PATH }}
          