apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1080
  selector:
    app: {{ .Values.nameOverride }}
  type: ClusterIP
