image:
  tag: 8.7.1-developer

service:
  type: ClusterIP

postgresql:
  persistence:
    size: 2Gi
  postgresqlUsername: postgres
  postgresqlDatabase: sonar
  existingSecret: sonar-postgresql
  existingSecretPasswordKey: postgresql-password

createPostgresqlSecret: false

nodeSelector:
  aex/devops: "true"

resources:
  requests:
    cpu: 0.25
    memory: 1.5Gi
  limits:
    cpu: 1
    memory: 6Gi
