statefulset:
  enabled: true

service:
  name: nexus
  type: ClusterIP
  enabled: true
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081

persistence:
  storageSize: 8Gi

nexusBackup:
  persistence:
    enabled: false

nexusProxy:
  enabled: false

nexus:
  imageName: sonatype/nexus3
  imageTag: 3.36.0
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 10
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 10
    failureThreshold: 20
  nodeSelector:
    aex/devops: "true"

  resources:
    requests:
      cpu: 0.25
      memory: 1.5Gi
