volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

esJavaOpts: "-Xmx2g -Xms2g"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    memory: 8Gi
