volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

esJavaOpts: "-Xmx2g -Xms2g"

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    memory: 8Gi

nodeSelector:
  aex/stable: "true"
