apiVersion: v1
kind: ConfigMap
metadata:
  name: freeradius-{{ .Values.instanceName }}
data:
  TZ: "Africa/Johannesburg"
  AUTH_LOG: "no"
  REPLY_LOG: "no"
  PRE_PROXY_LOG: "no"
  POST_PROXY_LOG: "no"
  DETAIL_LOG: "no"
  MAX_SERVERS: "30"
  ENABLE_PROXY: "yes"
  UPDATE_ACC_USERNAME: "yes"
  DATABASE_DIALECT: mssql
  DATABASE_DRIVER: rlm_sql_unixodbc
  DATABASE_HOST: database
  DATABASE_PORT: "3306"
  DATABASE_NAME: mpf_radius
  DATABASE_USERNAME: mitchells_radius
