{{- if and .Values.auth.type (ne .Values.auth.type "none") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
data:
  clientID: {{ b64enc .Values.oidc.clientId }}
  clientSecret: {{ b64enc .Values.oidc.clientSecret }}
{{- end }}
