# https://hub.docker.com/_/microsoft-dotnet-sdk
# docker build -t gitlab.vumaex.net:4567/internal/devops/dotnet-builder:5.0 .
# docker push gitlab.vumaex.net:4567/internal/devops/dotnet-builder:5.0
FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine
LABEL maintainer="Automation Exchange"
