apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-robot{{ .Values.user.clusterSuffix }}
  namespace: aex-devops

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps", "namespaces", "replicasets", "volumeattachments", "statefulsets", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["", "batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["", "apps"]
    resources: ["secrets"]
    verbs: ["list", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer
subjects:
  - kind: ServiceAccount
    name: ci-robot{{ .Values.user.clusterSuffix }}
    namespace: aex-devops
roleRef:
  kind: ClusterRole
  name: deployer
  apiGroup: rbac.authorization.k8s.io
