fullnameOverride: kibana-${suffix}
elasticsearchHosts: http://elastic-${suffix}:9200

resources:
  requests:
    cpu: 0.1
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi

nodeSelector:
  aex/devops: "true"
