# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
			source = "hashicorp/aws"
      version = "~> 4.0"
    }
    helm = {
			source = "hashicorp/helm"
      version = "~> 2.0"
    }
  }
}

provider aws {
	region = module.constants_cluster.aws_region
  profile = module.constants_cluster.aws_profile
}

provider aws {
	alias = "eu"
	region = "eu-west-1"
  profile = "vumatel-prod"
}

provider aws {
	alias = "dns"
  profile = "vumatel-operations"
	region = "af-south-1"
}
