{{ $deployName := .Values.serviceName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployName }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: {{ $deployName }}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: {{ .Values.subnets }}
spec:
  ports:
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: 69
  - name: test
    port: 70
    protocol: UDP
    targetPort: 70
  selector:
    app: {{ $deployName }}
  type: LoadBalancer
