# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
	required_providers {
		aws = {
			source = "hashicorp/aws"
			version = "~> 4.0"
		}
	}
}

provider aws {
	region = "af-south-1"
	profile = "vumatel-prod"
	default_tags {
		tags = {
			managed = "terraform"
		}
	}
}

provider aws {
	alias = "dns"
	profile = "vumatel-operations"
	region = "af-south-1"
	default_tags {
		tags = {
			managed = "terraform"
		}
	}
}
