volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

service:
  type: ${service_type}
  %{ if service_type == "LoadBalancer" }
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: ${name}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  %{ endif }
