apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: {{ .Chart.Name }}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: {{ join "," .Values.subnets }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "{{ gt (len .Values.subnets) 1 }}"
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
