{{- $deployName := include "deployName" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployName }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9292
  selector:
    app: {{ $deployName }}
  type: ClusterIP
